version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g npm
      - npm install
  build:
    commands:
      - npx prisma generate
      - npm run build

artifacts:
  files:
    - '**/*'
