version: '3.9'

services:
  backend:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shoppy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
